# Activity on the repository is the best way to provide input so that others can
# comment and see issues.  Presume the mediocre engineer goes for about $150k
# per year in SF and expect time boxes to be allocated accordingly.  Contact
# directly via contact@positron.solutions with "cargo2nix Professional Services"
# in the subject line.
github: positron-solutions
